# Generated by Django 3.1.4 on 2021-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbdl', '0003_auto_20210620_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='phone',
            field=models.CharField(default='+250', max_length=15),
        ),
    ]
